# -*- coding: utf-8 -*-
"""synset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/yagmurmutlu/432f9fab7b6dece6d2bc716a20a4589e/synset.ipynb
"""

import nltk
from nltk.corpus import wordnet

# WordNet verilerini indir
nltk.download('wordnet')

import nltk
from nltk.corpus import wordnet

# WordNet verilerini indir
nltk.download('wordnet')

def get_synsets(word):

    synsets = wordnet.synsets(word)
    synset_info = []

    for synset in synsets:
        synset_data = {}
        synset_data['definition'] = synset.definition()
        synset_data['lemmas'] = [lemma.name() for lemma in synset.lemmas()]
        synset_data['examples'] = [example.replace('_', ' ') for example in synset.examples()]
        synset_info.append(synset_data)

    return synset_info

def main():
    # Kullanıcıdan kelime al
    word = input("Lütfen bir kelime girin: ")

    # SynSet bilgilerini al
    synsets = get_synsets(word)

    # Kaç tane SynSet olduğunu ve bilgilerini ekrana yazdır
    print(f"'{word}' kelimesi için toplam {len(synsets)} adet SynSet bulunmaktadır.\n")

    for idx, synset in enumerate(synsets, 1):
        print(f"SynSet {idx}:")
        print(f"Tanım: {synset['definition']}")
        print(f"Lemmalar: {', '.join(synset['lemmas'])}")

        if synset['examples']:
            print(f"Örnekler: {', '.join(synset['examples'])}")

        print("-" * 50)

if __name__ == "__main__":
    main()

import nltk
from nltk.corpus import wordnet

# WordNet verilerini indir
nltk.download('wordnet')

def get_synsets(word):
    """
    Belirtilen kelime için SynSet bilgilerini döndürür.

    Parameters:
    word (str): İncelenecek kelime

    Returns:
    list: SynSet bilgileri
    """
    synsets = wordnet.synsets(word)
    synset_info = []

    for synset in synsets:
        synset_data = {}
        synset_data['definition'] = synset.definition()
        synset_data['lemmas'] = [lemma.name() for lemma in synset.lemmas()]
        synset_data['examples'] = [example.replace('_', ' ') for example in synset.examples()]
        synset_info.append(synset_data)

    return synset_info

def main():
    # Kullanıcıdan kelime al
    word = input("Lütfen bir kelime girin: ")

    # SynSet bilgilerini al
    synsets = get_synsets(word)

    # Kaç tane SynSet olduğunu ve bilgilerini ekrana yazdır
    print(f"'{word}' kelimesi için toplam {len(synsets)} adet SynSet bulunmaktadır.\n")

    for idx, synset in enumerate(synsets, 1):
        print(f"SynSet {idx}:")
        print(f"Tanım: {synset['definition']}")
        print(f"Lemmalar: {', '.join(synset['lemmas'])}")

        if synset['examples']:
            print(f"Örnekler: {', '.join(synset['examples'])}")

        print("-" * 50)

if __name__ == "__main__":
    main()